### ISSUE TITLE
Hola no se como hacer una pull request a tu repositorio

### ISSUE THREAD

**Issue by AlvarZenit** [johanderohan/DAM-2016#5]
Mi aplicación esta en este link:
https://github.com/AlvarZenit/practica3

**Comment by johanderohan** [comment]
Hola lo primero que tienes que hacer es un fork del repositorio. Con el botón superior derecho.
Una vez hecho clonas tu repositiorio y haces todos los cambios ahí. Cuando los tengas haces un commit y push hacía tu repositorio. Cuando lo tengas, si entras a github verás un botón de pull request.

Prueba a ver si lo consigues, cualquier duda me dices.

Saludos.

**Comment by AlvarZenit** [comment]
Hola. Creo q ya te he hecho el pull request, creia que ya lo habia hecho,
pero habia creado un repositorio mio con los originales, y le hice un pull
con la practica. En cualquier caso, ya deberias tenerlo.
Saludos.

**Comment by johanderohan** [comment]
Sí, ya la he recibido y se la he enviado a Diego ;)
